id = "molten-theme"
name = "Molten Theme"
version = "1.0.0"
schema_version = 1
authors = ["Vaqxai <vaqxai@gmail.com>"]
description = "A red-orange-dark theme for your editor. Derived from Ayu Dark."
repository = "https://github.com/vaqxai/zed-ash-theme"
